// Downloads the site's Google Fonts (Chakra Petch, IBM Plex Mono, Spectral — all SIL Open Font License) into
// fonts/ so the app renders its own type offline. Run once (npm run fonts); the result is committed.
const fs = require("fs"), path = require("path");
const OUT = path.join(__dirname, "fonts");
const CSS_URL = "https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500;600&family=Spectral:ital,wght@0,400;0,500;0,600;1,400&display=swap";
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15";

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();
  // keep the latin and latin-ext subsets only; each @font-face is preceded by a /* subset */ comment
  const blocks = css.split(/(?=\/\* [a-z-]+ \*\/)/).filter((b) => /^\/\* latin(-ext)? \*\//.test(b));
  let out = "/* Self-hosted copies of the site's Google Fonts (SIL OFL). Generated by fetch-fonts.js. */\n";
  let n = 0;
  for (const b of blocks) {
    const fam = /font-family:\s*'([^']+)'/.exec(b)[1].replace(/\s+/g, "");
    const wgt = /font-weight:\s*(\d+)/.exec(b)[1], sty = /font-style:\s*(\w+)/.exec(b)[1];
    const sub = /^\/\* ([a-z-]+) \*\//.exec(b)[1];
    const url = /url\((https:[^)]+)\)/.exec(b)[1];
    const file = `${fam}-${wgt}${sty === "italic" ? "i" : ""}-${sub}.woff2`;
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    fs.writeFileSync(path.join(OUT, file), buf); n++;
    out += b.replace(url, file) + "\n";
  }
  fs.writeFileSync(path.join(OUT, "fonts.css"), out);
  console.log(`fonts: ${n} files written to ${OUT}`);
}
main().catch((e) => { console.error("FAIL " + e.message); process.exit(1); });
